const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('picoFlash', {
  minimize: () => ipcRenderer.send('window:minimize'),
  maximize: () => ipcRenderer.send('window:maximize'),
  close: () => ipcRenderer.send('window:close'),
  getConfig: () => ipcRenderer.invoke('setup:getConfig'),
  runSetup: (d) => ipcRenderer.invoke('setup:run', d),
  boardList: () => ipcRenderer.invoke('setup:boardList'),
  onNeedsSetup: (cb) => ipcRenderer.on('app:needsSetup', (_, v) => cb(v)),
  needsSetup: () => ipcRenderer.invoke('app:needsSetup'),
  onSetupProgress: (cb) => ipcRenderer.on('setup:progress', (_, v) => cb(v)),
  onSetupLog: (cb) => ipcRenderer.on('setup:log', (_, v) => cb(v)),
  onSetupDone: (cb) => ipcRenderer.on('setup:done', (_, v) => cb(v)),
  onSetupError: (cb) => ipcRenderer.on('setup:error', (_, v) => cb(v)),
  startFlash: () => ipcRenderer.invoke('flash:start'),
  onFlashProgress: (cb) => ipcRenderer.on('flash:progress', (_, v) => cb(v)),
  onFlashLog: (cb) => ipcRenderer.on('flash:log', (_, v) => cb(v)),
  onFlashDone: (cb) => ipcRenderer.on('flash:done', (_, v) => cb(v)),
  onFlashError: (cb) => ipcRenderer.on('flash:error', (_, v) => cb(v)),
  onDeviceStatus: (cb) => ipcRenderer.on('device:status', (_, v) => cb(v)),
  setupSwapPayload: (n) => ipcRenderer.invoke('setupMode:swapPayload', n),
  setupListFiles: () => ipcRenderer.invoke('setupMode:listFiles'),
  setupDownloadFile: (n) => ipcRenderer.invoke('setupMode:downloadFile', n),
  setupEject: () => ipcRenderer.invoke('setupMode:eject'),
  listPayloads: () => ipcRenderer.invoke('payload:list'),
  armPayload: (n) => ipcRenderer.invoke('payload:arm', n),
  readPayload: (n) => ipcRenderer.invoke('payload:read', n),
  savePayload: (n, t) => ipcRenderer.invoke('payload:save', n, t),
  importPayload: () => ipcRenderer.invoke('payload:import'),
  deletePayload: (n) => ipcRenderer.invoke('payload:delete', n),
  onPickPayload: (cb) => ipcRenderer.on('flash:pickPayload', (_, v) => cb(v)),
  choosePayload: (n) => ipcRenderer.send('flash:payloadChosen', n),
  getWifi: () => ipcRenderer.invoke('wifi:get'),
  saveWifi: (s, p) => ipcRenderer.invoke('wifi:save', { ssid: s, password: p }),
  reconfigure: () => ipcRenderer.invoke('app:reconfigure'),
  recorderStart: () => ipcRenderer.invoke('recorder:start'),
  recorderStop: () => ipcRenderer.invoke('recorder:stop'),
  recorderSave: (n, s) => ipcRenderer.invoke('recorder:save', n, s),
})
